config/routes.rb
Rails.application.routes.draw do
  resources :shoes
  resources :comments
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  # get 'profile/:id', to: 'users#profile', as: 'user_profile'

  # Mount ActionCable
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  scope :by_name, -> { order(name: :asc) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shoe

  after_create_commit { CommentBroadcastJob.perform_later(self) }

  validates :body, presence: true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :user
  after_initialize :default_images
  scope :default_sort, -> { order(updated_at: :desc) }
  has_many :comments, dependent: :destroy
  validates :name, presence: true, length: { maximum: 24 }
  mount_uploader :main_image, ShoeUploader
  mount_uploader :thumb_image, ShoeUploader

  def default_images
    if !main_image && !thumb_image
      self.main_image = "https://s3-us-west-1.amazonaws.com/kickscollective/air-jordan-3-silhouette.png"
      self.thumb_image = "https://s3-us-west-1.amazonaws.com/kickscollective/air-jordan-3-silhouette.png"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shoes, dependent: :destroy
  has_one :inventory, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseWhitelist, SessionRedirect
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/concerns/session_redirect.rb
module SessionRedirect
  extend ActiveSupport::Concern
  def after_sign_in_path_for(resource)
    shoes_path
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]
  layout "application"

    def index
      @shoes = Shoe.includes(:comments).all.default_sort
    end

    def show
      @comment = Comment.new
    end

    def new
      @shoe = Shoe.new
      @brands = Brand.all.by_name
    end

    def edit
    end

    def create
      @shoe = Shoe.new(shoe_params)
      @shoe.user_id = current_user.id

      respond_to do |format|
        if @shoe.save
          format.html { redirect_to shoes_path, notice: 'Shoe was successfully created.' }
        else
          # puts "Something went wrong"
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @shoe.update(shoe_params)
          format.html { redirect_to shoe_path(@shoe), notice: 'Shoe was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @shoe.destroy
      respond_to do |format|
        format.html { redirect_to shoes_path, notice: 'Sample was successfully destroyed.' }
      end
    end

    private
      # Never trust parameters from the scary internet, only allow the white list through.
      def shoe_params
        params.require(:shoe).permit(:name, :price, :brand, :main_image, :thumb_image)
      end

      def set_shoe
        @shoe= Shoe.includes(:comments).find(params[:id])
        @brands = Brand.all.by_name
      end
      
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout "portal"
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def back_to_marketplace
    if params[:controller] == "shoes"  && params[:action] == "show"
      link_to "Back To Marketplace", shoes_path
    end
  end

  def login_helper
    if user_signed_in?
      render partial: 'shared/signed_in_links'
    else
      render partial: 'shared/no_account_links'
    end
  end

  def portal_button
    if user_signed_in?
      link_to "Back To Marketplace", shoes_path, class: "btn btn-lg btn-info"
    else
      render partial: 'shared/no_session_portal_links'
    end
  end

  def alerts
    if notice
      '<p class="notice">'.html_safe + notice + '</p>'.html_safe
    elsif alert
      '<p class="alert">'.html_safe + alert + '</p>'.html_safe
    end
  end

  def user_badges(user)
    if user.reputation > 6
      '<span class="badge badge-pill badge-success"> Reputable Seller </span>'.html_safe
    end
  end

  def edit_authorization(shoe)
    if current_user == shoe.user
      render partial: 'shared/edit_links', locals: {shoe: shoe}
    end
  end

  def session_greeting
    if user_signed_in?
      '<h3>Welcome back '.html_safe + current_user.username + ' !</h3>'.html_safe
    else
      '<h3>Create an account so you can start posting!</h3'.html_safe
    end
  end

  def action_button_for_forms(form)
    if params[:action] == "edit"
      form.submit "Update", class: 'form-btn'
    else
      form.submit "Post", class: 'form-btn'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment-card">
  <div class="card">
    <div class="card-block">
      <div class="row">
        <div class="col-md-2 username-col">
          <%= comment.user.username %>
          <div class="timestamp-col">
            <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago
          </div>
        </div>
        <div class="col-md-10">
          <%= comment.body %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KicksCollective</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Yellowtail" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
  </head>
  <body>
    <%= render 'shared/nav' %>
    <!-- <%= alerts %> -->
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/portal.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KicksCollective</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'portal', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'portal', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
  </head>

  <body>
    <!-- <%= render 'shared/nav' %> -->
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_edit_links.html.erb
<%= link_to "Edit Listing", edit_shoe_path(shoe), class: 'btn btn-warning' %>
<%= link_to 'Delete Listing', shoe, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

app/views/shared/_footer.html.erb
<div class="footer-section">
  <div class="row">
    <div class="col-md-6 footer-col">
    </div>
    <div class="col-md-6 footer-col">
      <span class="copyright">&copy Kicks<span class="red-collective">Collective</span> Est. 2018</span>
      <div class="social-media">
        <%= image_tag 'instagram.png', class:'ig-logo' %>
        <%= image_tag 'facebook.png' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-dark my-navbar">
  <a class="navbar-brand" href="/">K<span class="red-collective-header">C</a>
    <%= back_to_marketplace %>
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Menu
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%= login_helper %>
    </div>
</nav>

app/views/shared/_no_account_links.html.erb
<%= link_to "Log In", new_user_session_path , class: 'dropdown-item' %>
<%= link_to "Register", new_user_registration_path , class: 'dropdown-item' %>

app/views/shared/_no_session_portal_links.html.erb
<%= link_to "Create An Account", new_user_registration_path, class: "btn btn-lg btn-info" %>
<%= link_to "Returning Users", new_user_session_path, class: "btn btn-lg btn-info" %>

app/views/shared/_signed_in_links.html.erb
<div class="dropdown-item no-hover">Hey, <%= current_user.username %></div>
<%= link_to "Create a new listing", new_shoe_path , class: 'dropdown-item' %>
<%= link_to "Log Out", destroy_user_session_path , class: 'dropdown-item', :method => :delete  %>

app/views/shoes/_comment_form.html.erb
<%= form_for @comment, url:'#' do |f|%>
  <div class="form-group">
    <!-- <%= f.label :body %> -->
    <%= f.text_area :body, class: "form-control" %>
    <%= f.submit 'Comment', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shoes/_form.html.erb
<div class="container-fluid login-page-container">
  <div class="container new-shoe-container">
  <h2 class="form-header">Shoe Details</h2>
  <%= form_for(@shoe) do |form| %>

    <div class="field">
      <%= form.text_field :name, maxlength: 20, placeholder: 'name' %>
    </div>

    <div class="field">
      <%= form.number_field :price, placeholder: 'price' %>
    </div>

    <div class="field">
      <%= form.text_field :brand, placeholder: 'brand' %>
    </div>

    <div class="field">
      <label class="btn btn-info upload-btn">
        Upload a main image file <%= form.file_field :main_image, style: 'display:none;' %>
      </label>
    </div>

    <div class="field">
      <label class="btn btn-info upload-btn">
        Upload a thumb image file <%= form.file_field :thumb_image, style: 'display:none;' %>
      </label>
    </div>

    <div class="actions">
      <%= action_button_for_forms(form) %>
    </div>
    <% end %>
  </div>
</div>

app/views/shoes/_shoes.html.erb
<% @shoes.each do |shoe| %>
<div class="col-md-4">
  <div class="card shoe-card">
    <%= image_tag shoe.thumb_image.url, class: "card-picture" %>
      <div class="card-overlay">
        <span class="badge badge-pill badge-danger">
          <%= shoe.brand %>
        </span>
        </div>
        <div class="card-body">
          <div class="news-title">
            <h5 class=" title-small">
              <%= link_to shoe.name, shoe_path(shoe)%>
              <br/>
              <%= user_badges(shoe.user) %>
              <br/>
              Asking Price: <%= number_to_currency(shoe.price) %>
            </h5>
          </div>
          <p class="card-text">
            <small class="text-time">
              Created <%= distance_of_time_in_words(shoe.created_at, Time.now) %> ago
              <br/>
              Offered by <%= shoe.user.username %>
            </small>
          </p>
        </div>
      </div>
    </div>
<% end %>

app/views/shoes/edit.html.erb
<h1>New Shoe Listing</h1>

<%= render 'form', shoe: @shoe %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
<!-- <%= session_greeting %> -->
<div class="container-fluid fluid-header">
  <span class="section-text"> marketplace </span>
</div>
<div class="container listings-container">
  <div class="row">
    <%= render 'shoes' %>
  </div>
</div>

app/views/shoes/new.html.erb
<h1>New Shoe Listing</h1>

<%= render 'form', shoe: @shoe %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<div class="container shoe-listing-show-wrapper">
  <div class="container shoe-listing-details">
    <h2 class="listing-name"> <%= @shoe.name %> </h1>
    <p> <%= image_tag @shoe.main_image.url, style: "width: 100%"%> </p>
    <p> BIN: <%= number_to_currency(@shoe.price) %> </p>
    <p> Posted by <%= @shoe.user.username %></p>
    <p> <%= user_badges(@shoe.user) %>
    <p> <%= edit_authorization(@shoe) %>
    <p> Created <%= distance_of_time_in_words(@shoe.created_at, Time.now) %> ago</p>

    <!-- Start of comments form  -->
    <!-- Url hash parameter prevents from sending to a new controller/page -->
    <%= render 'shoes/comment_form' %>
    <!-- End of comments form -->

    <div id ="comments" data-shoe-id="<%= @shoe.id%>">
      <h2 class="comment-header"> Comments Thread </h2>
      <%= render @shoe.comments %>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <!-- <h3 class="masthead-brand">KC</h3> -->
      <nav class="nav nav-masthead justify-content-center">
      </nav>
    </div>
  </header>


  <h1 class="kc-welcome"> Welcome To <br/> <span class="kc-span"> KICKSCOLLECTIVE </span> </h1>
  <main role="main" class="inner cover">
    <p class="lead">The Sneaker Community for Sneakerheads</p>
    <p class="lead">
    <%= portal_button %>
    </p>
  </main>
  <footer class="mastfoot mt-auto">
    <div class="inner">
    </div>
  </footer>
</div>

app/views/users/profile.html.erb
<h1> Welcome to <%= @user.username %>'s profile page </h1>